// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package icalendar.actions;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import icalendar.proxies.Attendee;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_ICalFile extends UserAction<java.lang.Boolean>
{
	private final java.lang.String UID;
	private final java.lang.Long Sequence;
	private final icalendar.proxies.ENUM_ICalStatus Status;
	private final java.util.Date StartDateTime;
	private final java.util.Date EndDateTime;
	private final java.lang.Boolean Localized;
	private final java.lang.String TimeZoneCode;
	private final java.lang.String Subject;
	private final java.lang.String BodyText;
	private final java.lang.String Location;
	private final java.lang.String OrganizerName;
	private final java.lang.String OrganizerEmail;
	/** @deprecated use com.mendix.utils.ListUtils.map(AttendeeList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __AttendeeList;
	private final java.util.List<icalendar.proxies.Attendee> AttendeeList;
	/** @deprecated use IcalFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __IcalFile;
	private final system.proxies.FileDocument IcalFile;

	public JA_ICalFile(
		IContext context,
		java.lang.String _uID,
		java.lang.Long _sequence,
		java.lang.String _status,
		java.util.Date _startDateTime,
		java.util.Date _endDateTime,
		java.lang.Boolean _localized,
		java.lang.String _timeZoneCode,
		java.lang.String _subject,
		java.lang.String _bodyText,
		java.lang.String _location,
		java.lang.String _organizerName,
		java.lang.String _organizerEmail,
		java.util.List<IMendixObject> _attendeeList,
		IMendixObject _icalFile
	)
	{
		super(context);
		this.UID = _uID;
		this.Sequence = _sequence;
		this.Status = _status == null ? null : icalendar.proxies.ENUM_ICalStatus.valueOf(_status);
		this.StartDateTime = _startDateTime;
		this.EndDateTime = _endDateTime;
		this.Localized = _localized;
		this.TimeZoneCode = _timeZoneCode;
		this.Subject = _subject;
		this.BodyText = _bodyText;
		this.Location = _location;
		this.OrganizerName = _organizerName;
		this.OrganizerEmail = _organizerEmail;
		this.__AttendeeList = _attendeeList;
		this.AttendeeList = java.util.Optional.ofNullable(_attendeeList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(attendeeListElement -> icalendar.proxies.Attendee.initialize(getContext(), attendeeListElement))
			.collect(java.util.stream.Collectors.toList());
		this.__IcalFile = _icalFile;
		this.IcalFile = _icalFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _icalFile);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        if (IcalFile == null) {
            LOG.error("No file provided");
            return false;
        }
        if (Status == null) {
            LOG.error("No status set");
            return false;
        }
        if (StartDateTime == null || EndDateTime == null) {
            LOG.error("Start or end date/time not set");
            return false;
        }

        // Localized == true  -> the value is a real moment in time; emit as UTC (trailing Z), no TZID.
        // Localized == false/null -> the value is a wall-clock label; emit the digits verbatim under
        //                            the given TZID (the original behaviour of this action).
        boolean treatAsMoment = Boolean.TRUE.equals(Localized);

        String localTimeZoneCode = this.TimeZoneCode;
        if (localTimeZoneCode == null) {
            localTimeZoneCode = ZoneId.systemDefault().getId();
        }

        String method = Status.toString();

        StringBuilder icalBuilder = new StringBuilder();
        appendLine(icalBuilder, "BEGIN:VCALENDAR");
        appendLine(icalBuilder, "VERSION:2.0");
        appendLine(icalBuilder, "CALSCALE:GREGORIAN");
        appendLine(icalBuilder, "METHOD:" + method);
        appendLine(icalBuilder, "PRODID:-//Mendix//iCal4j");

        appendLine(icalBuilder, "BEGIN:VEVENT");
        appendLine(icalBuilder, "UID:" + UID);
        // DTSTAMP is the creation time of this iCal object — always a true moment, so always UTC.
        appendLine(icalBuilder, "DTSTAMP:" + UTC_STAMP.format(Instant.now()));
        appendLine(icalBuilder, dateProperty("DTSTART", StartDateTime.toInstant(), treatAsMoment, localTimeZoneCode));
        appendLine(icalBuilder, dateProperty("DTEND",   EndDateTime.toInstant(),   treatAsMoment, localTimeZoneCode));
        appendLine(icalBuilder, "SUMMARY:" + escapeText(Subject));
        appendLine(icalBuilder, "SEQUENCE:" + Sequence);
        appendLine(icalBuilder, "ORGANIZER;CN=\"" + escapeText(OrganizerName) + "\":mailto:" + OrganizerEmail);

        for (Attendee attendee : AttendeeList) {
            try {
                String partstat = attendee.getStatus() != null
                        ? attendee.getStatus().getCaption()
                        : "NEEDS-ACTION";
                String email = attendee.getEmail();
                if (email == null) {
                    LOG.warn("Skipping attendee without an email address");
                    continue;
                }
                appendLine(icalBuilder,
                        "ATTENDEE;PARTSTAT=" + partstat
                        + ";CN=\"" + escapeText(attendee.getFullname()) + "\":mailto:" + email);
            } catch (Exception e) {
                LOG.error("Could not parse the Attendees, you should not rename the entity Attendee or any of the attributes", e);
            }
        }

        if (Location != null) {
            appendLine(icalBuilder, "LOCATION:" + escapeText(Location));
        }
        if (BodyText != null) {
            appendLine(icalBuilder, "DESCRIPTION:" + escapeText(BodyText));
        }

        appendLine(icalBuilder, "END:VEVENT");
        appendLine(icalBuilder, "END:VCALENDAR");

        byte[] byteArray = icalBuilder.toString().getBytes(StandardCharsets.UTF_8);
        try (InputStream is = new ByteArrayInputStream(byteArray)) {
            Core.storeFileDocumentContent(getContext(), this.__IcalFile, is);
            this.IcalFile.setName(getContext(), "event.ics");
        } catch (Exception e) {
            LOG.error("Failed to store the iCal file content", e);
            return false;
        }
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ICalFile";
	}

	// BEGIN EXTRA CODE
    /**
     * Formats a date-time content line.
     * treatAsMoment = true  -> "<NAME>:<utc>Z"            (real instant, universal)
     * treatAsMoment = false -> "<NAME>;TZID=<tzid>:<digits>" (wall-clock label, verbatim)
     */
    private static String dateProperty(String name, Instant instant, boolean treatAsMoment, String tzid) {
        if (treatAsMoment) {
            return name + ":" + UTC_STAMP.format(instant);
        }
        return name + ";TZID=" + tzid + ":" + UTC_DIGITS.format(instant);
    }

    /** Escapes a TEXT value per RFC 5545 §3.3.11. Backslash must be escaped first. */
    private static String escapeText(String value) {
        if (value == null) return "";
        return value
                .replace("\\", "\\\\")
                .replace(";", "\\;")
                .replace(",", "\\,")
                .replace("\r\n", "\\n")
                .replace("\n", "\\n")
                .replace("\r", "\\n");
    }

    /** Folds a content line to <=75 octets per RFC 5545 §3.1, never splitting a multi-byte char. */
    private static String fold(String line) {
        if (line.getBytes(StandardCharsets.UTF_8).length <= 75) return line;
        StringBuilder sb = new StringBuilder();
        int count = 0;
        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);
            int charBytes = String.valueOf(c).getBytes(StandardCharsets.UTF_8).length;
            if (count + charBytes > 73) {
                sb.append("\r\n ");
                count = 1; // leading space counts toward the line length
            }
            sb.append(c);
            count += charBytes;
        }
        return sb.toString();
    }

    /** Folds the line and terminates it with CRLF. */
    private static void appendLine(StringBuilder sb, String line) {
        sb.append(fold(line)).append("\r\n");
    }

    private static final DateTimeFormatter UTC_STAMP =
            DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss'Z'").withZone(java.time.ZoneOffset.UTC);
    private static final DateTimeFormatter UTC_DIGITS =
            DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss").withZone(java.time.ZoneOffset.UTC);

    public static ILogNode LOG = Core.getLogger("iCalendar");
	// END EXTRA CODE
}
